### ISSUE TITLE
urllib Connection error

### ISSUE THREAD

**Issue by jj4giya** [vndee/local-talking-llm#2]
`Assistant started! Press Ctrl+C to exit.
Press Enter to start recording, then press Enter again to stop.

You: I
Traceback (most recent call last):
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 400, in request
    self.endheaders()
  File "C:\Program Files\Python\Python311\Lib\http\client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python\Python311\Lib\http\client.py", line 1041, in _send_output
    self.send(msg)
  File "C:\Program Files\Python\Python311\Lib\http\client.py", line 979, in send
    self.connect()
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 238, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001D9DE35C9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9DE35C9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\david\Downloads\mz\local-talking-llm\app.py", line 139, in <module>
    response = get_llm_response(text)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Downloads\mz\local-talking-llm\app.py", line 86, in get_llm_response
    response = chain.predict(input=text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain\chains\llm.py", line 293, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain_core\_api\deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 378, in __call__
    return self.invoke(
           ^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 163, in invoke
    raise e
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain\chains\llm.py", line 103, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain\chains\llm.py", line 115, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain_core\language_models\llms.py", line 569, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain_core\language_models\llms.py", line 748, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain_core\language_models\llms.py", line 606, in _generate_helper
    raise e
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain_core\language_models\llms.py", line 593, in _generate_helper
    self._generate(
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain_community\llms\ollama.py", line 421, in _generate
    final_chunk = super()._stream_with_aggregation(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain_community\llms\ollama.py", line 330, in _stream_with_aggregation
    for stream_resp in self._create_generate_stream(prompt, stop, **kwargs):
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain_community\llms\ollama.py", line 172, in _create_generate_stream
    yield from self._create_stream(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langchain_community\llms\ollama.py", line 233, in _create_stream
    response = requests.post(
               ^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9DE35C9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`

Can't figure out how to fix it. Mostly all the solutions said close proxy but didn't work for me. Would appreciate any help thanks

**Comment by jj4giya** [comment]
changing the default port for ollama helped...
